### ISSUE TITLE
[Suggest]: チェックの除外

### ISSUE THREAD

**Issue by tmarcus87** [Warashi/wrapmsg#21]
### What are you frustrated with?

特定のエラーでチェックをスキップしたい

### What feature would resolve your frustration?

以下のような `// nolint:` などによるスキップ機能がほしい
```
if err := foo(bar); err != nil {
  // nolint:wrapmsg
  return fmt.Errorf("failed to foo w/ %v : %w", bar, err)
}

```

**Comment by Warashi** [comment]
これを使えば実現できそうですね
https://pkg.go.dev/github.com/kyoh86/nolint
